#target dependencies action is the basic of a makefile 
#target: dependencies
#	action		#this is a table before action, and it is must be there



fork1: fork1.o
	g++ fork1.o -o fork1

fork1.o: fork1.cpp
	g++ -c fork1.cpp

clean: 
	rm -rf *.o fork1